# Generated by Django 2.1.4 on 2019-01-25 13:36

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiveLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(default=True, null=True)),
                ('audit', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_change_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default=None, null=True)),
                ('give_a_like', models.IntegerField(default=0)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Plate', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.BooleanField(default=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('avatar', models.ImageField(default=None, null=True, upload_to=user.models.avatar)),
                ('description', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', to_field='nickname'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='user.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', to_field='nickname'),
        ),
        migrations.AddField(
            model_name='plate',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User', to_field='nickname'),
        ),
        migrations.AddField(
            model_name='givelike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Post'),
        ),
        migrations.AddField(
            model_name='givelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
    ]
